export const CREAT_SHOE_SUCCESS = "CREAT_SHOE_SUCCESS";
export const UPDATE_SHOE_SUCCESS = "UPDATE_SHOE_SUCCESS";
export const DELETE_SHOE_SUCCESS = "DELETE_SHOE_SUCCESS";
export const LOAD_SHOES_SUCCESS = "LOAD_SHOES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const ERROR_API_CALL = "ERROR_API_CALL";
