export const CREAT_SHOE_SUCCESS = "CREAT_SHOE";
export const UPDATE_SHOE_SUCCESS = "UPDATE_SHOE";
export const DELETE_SHOE = "DELETE_SHOE";
export const LOAD_SHOES_SUCCESS = "LOAD_SHOES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
